name:
  .NET

on:
  pull_request:
  push:
    branches: master

jobs:
  welcome:
    runs-on: ubuntu-latest

    steps:
    - name: Print welcome message
      run: echo "Hello World!"
  
  build:
    needs: welcome
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.x.x'
    - run: dotnet build
    
  test:
    needs: [welcome, build]
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.x.x'
    - run: dotnet test
 
